runreg/models.py
from enum import Enum
from typing import Optional

from flask_login import UserMixin
from quart_sqlalchemy.model.mixins import SimpleDictMixin
from sqlalchemy.orm import Mapped, mapped_column, relationship            # type: ignore[attr-defined]
from sqlalchemy.schema import Column, ForeignKey, Table
from sqlalchemy.types import Integer, String, Enum as SQLEnum

from runreg.database import Model


runner_types_tags_table = Table(
    'runner_types_tags',
    Model.metadata,
    Column('runner_type_id', ForeignKey('runner_types.id')),
    Column('tag_id', ForeignKey('tags.id'))
)


class Status(Enum):
    Unregistered = 'unregistered'
    Pending = 'pending'
    Active = 'active'
    Deleted = 'deleted'


class User(Model, UserMixin):
    __tablename__ = 'users'

    id: Mapped[int] = mapped_column(primary_key=True, autoincrement=True)
    email: Mapped[str] = mapped_column(String(255))
    password: Mapped[Optional[str]] = mapped_column(String(255))
    access_token: Mapped[Optional[str]] = mapped_column(String(255))
    is_active: Mapped[bool] = mapped_column(default=True)

    runners: Mapped[list['Runner']] = relationship('Runner', back_populates='user')

    def get_id(self):
        return self.email


class Tag(Model, SimpleDictMixin):
    __tablename__ = 'tags'

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    name: Mapped[str] = mapped_column(String(255))


class RunnerType(Model, SimpleDictMixin):
    __tablename__ = 'runner_types'

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    name: Mapped[str] = mapped_column(String(255))

    tags: Mapped[list[Tag]] = relationship(Tag, secondary=runner_types_tags_table)


class Runner(Model, SimpleDictMixin):
    __tablename__ = 'runners'

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    runner_type_id: Mapped[int] = mapped_column(Integer, ForeignKey('runner_types.id'))
    user_id: Mapped[int] = mapped_column(Integer, ForeignKey('users.id'))
    token: Mapped[str] = mapped_column(String(255))
    name: Mapped[str] = mapped_column(String(255))
    description: Mapped[Optional[str]] = mapped_column(String(255))
    status: Mapped[str] = mapped_column(SQLEnum(Status), default=Status.Unregistered)

    runner_type: Mapped[RunnerType] = relationship(RunnerType)
    user: Mapped[User] = relationship(User, back_populates='runners')

runreg/__init__.py
# SPDX-FileCopyrightText: 2023-present Raoul Snyman <raoul@snyman.info>
#
# SPDX-License-Identifier: MIT

runreg/app.py
import quart_flask_patch                    # noqa: F401
from quart import Quart

from runreg.auth import login_manager
from runreg.database import db
from runreg.config import get_quart_config
from runreg.views.auth import auth
from runreg.views.runners import runners


def make_app():
    """A function to create the application object"""
    app = Quart('runreg')
    get_quart_config(app.config)
    db.init_app(app)
    db.create_all()
    login_manager.init_app(app)

    app.register_blueprint(auth)
    app.register_blueprint(runners)
    return app

runreg/auth.py
from flask_login import LoginManager
from sqlalchemy.sql.expression import select

from runreg.database import session
from runreg.models import User


login_manager = LoginManager()
login_manager.login_view = 'auth.login'


@login_manager.user_loader
def user_loader(email):
    with session() as s:
        user = s.scalars(select(User).where(User.email == email, User.is_active == True)).first()  # noqa: E712
    return user


@login_manager.request_loader
def request_loader(request):
    if request.authorization:
        with session() as s:
            user = s.scalars(select(User).where(User.access_token == request.authorization.token,
                                                User.is_active == True)).first()  # noqa: E712
        return user
    return None

runreg/views/auth.py
from flask_login import login_user, logout_user
from quart import Blueprint, request, redirect
from quart.templating import render_template as render
from sqlalchemy.sql.expression import select

from runreg.bcrypt import bcrypt
from runreg.database import session
from runreg.models import User

auth = Blueprint('auth', __name__)


@auth.route('/login', methods=['GET', 'POST'])
async def login():
    if request.method == 'POST':
        form = await request.form
        if form.get('email') and form.get('password'):
            with session() as s:
                user = s.scalars(select(User).where(User.email == form.get('email'))).first()
            if user and bcrypt.check_password_hash(user.password, form.get('password')):
                login_user(user)
                return redirect('/runners')
            else:
                print(user)
    return await render('login.html')


@auth.route('/logout', methods=['GET'])
async def logout():
    logout_user()
    return redirect('/')

runreg/views/runners.py
from quart import Blueprint, request, redirect
from quart.templating import render_template as render
from flask_login import login_required, current_user
from sqlalchemy.sql.expression import select

from runreg.database import session
from runreg.models import Runner, RunnerType, Status


runners = Blueprint('runners', __name__, url_prefix='/runners')


@runners.route('', methods=['GET'])
@login_required
async def all():
    """Return all the runners"""
    with session() as s:
        rs = s.scalars(select(Runner).where(Runner.user == current_user)).all()
        return await render('runners.html', runners=rs)


@runners.route('/register', methods=['GET', 'POST'])
@login_required
async def register():
    """Register a new runner"""
    if request.method == 'POST':
        form = await request.form
        if form.get('runner-type') and form.get('token'):
            with session() as s:
                runner_type = s.get(RunnerType, form.get('runner-type'))
                runner = Runner(
                    name=form.get('name'),
                    description=form.get('description'),
                    token=form.get('token'),
                    runner_type=runner_type,
                    user=current_user
                )
                s.add(runner)
                s.commit()
            return redirect('/runners')
    with session() as s:
        runner_types = s.scalars(select(RunnerType)).all()
        return await render('register.html', runner_types=runner_types)


@runners.route('/unregistered/<int:runner_type_id>', methods=['GET'])
@login_required
async def unregistered(runner_type_id):
    """Return all the runners"""
    runners_list = []
    with session() as s:
        runner_type = s.get(RunnerType, runner_type_id)
        if not runner_type:
            return {'runners': []}
        rs = s.scalars(select(Runner).where(Runner.user == current_user, Runner.runner_type == runner_type,
                                            Runner.status == Status.Unregistered)).all()
        for runner in rs:
            d = runner.to_dict()
            d['runner_type'] = runner.runner_type.to_dict()
            d['status'] = d['status'].name
            d['runner_type']['tags'] = [tag.to_dict() for tag in runner.runner_type.tags]
            runners_list.append(d)
            # Update status to pending
            runner.status = Status.Pending
        s.add_all(rs)
        s.commit()
    return {'runners': runners_list}


@runners.route('/<int:runner_id>/set-active', methods=['POST'])
@login_required
async def set_active(runner_id):
    with session() as s:
        runner = s.get(Runner, runner_id)
        if runner:
            runner.status = Status.Active
            s.add(runner)
            s.commit()
            pass
        else:
            return 'Not found', 404
    return ''


@runners.route('/<int:runner_id>/set-unregistered', methods=['POST'])
@login_required
async def set_unregistered(runner_id):
    with session() as s:
        runner = s.get(Runner, runner_id)
        if runner:
            runner.status = Status.Unregistered
            s.add(runner)
            s.commit()
            pass
        else:
            return 'Not found', 404
    return ''

runreg/templates/base.html
<!doctype html>
<html lang="en" data-bs-theme="auto">
  <head>
    <script src="{{ url_for('static', filename='js/color-modes.js') }}"></script>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Runner self-registration</title>
    <link href="{{ url_for('static', filename='css/bootstrap.min.css') }}" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css" rel="stylesheet">
    <link href="{{ url_for('static', filename='css/global.css') }}" rel="stylesheet">
    {% block extrastyles %}{% endblock %}
    <link rel="icon" href="{{ url_for('static', filename='images/server.svg') }}">
  </head>
  <body class="{% block bodyclasses %}{% endblock %}">
    <div class="dropdown position-fixed bottom-0 end-0 mb-3 me-3 bd-mode-toggle">
      <button class="btn btn-bd-primary py-2 dropdown-toggle d-flex align-items-center"
              id="bd-theme"
              type="button"
              aria-expanded="false"
              data-bs-toggle="dropdown"
              aria-label="Toggle theme (auto)">
        <div class="theme-icon-active" width="1em" height="1em"><i class="bi-sun-fill"></i></div>
        <span class="visually-hidden" id="bd-theme-text">Toggle theme</span>
      </button>
      <ul class="dropdown-menu dropdown-menu-end shadow" aria-labelledby="bd-theme-text">
        <li>
          <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="light" aria-pressed="false">
            <div class="me-2 opacity-50 theme-icon" width="1em" height="1em"><i class="bi-sun-fill"></i></div>
            Light
            <div class="ms-auto d-none" width="1em" height="1em"><i class="bi-check2"></i></div>
          </button>
        </li>
        <li>
          <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="dark" aria-pressed="false">
            <div class="me-2 opacity-50 theme-icon" width="1em" height="1em"><i class="bi-moon-stars-fill"></i></div>
            Dark
            <div class="ms-auto d-none" width="1em" height="1em"><i class="bi-check2"></i></div>
          </button>
        </li>
        <li>
          <button type="button" class="dropdown-item d-flex align-items-center active" data-bs-theme-value="auto" aria-pressed="true">
            <div class="me-2 opacity-50 theme-icon" width="1em" height="1em"><i class="bi-circle-half"></i></div>
            Auto
            <div class="ms-auto d-none" width="1em" height="1em"><i href="bi-check2"></i></div>
          </button>
        </li>
      </ul>
    </div>
    {% block layout %}{% endblock %}
    <script src="{{ url_for('static', filename='js/bootstrap.bundle.min.js') }}" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js@4.2.1/dist/chart.umd.min.js" integrity="sha384-gdQErvCNWvHQZj6XZM0dNsAoY4v+j5P1XDpNkcM3HJG1Yx04ecqIHk7+4VBOCHOG" crossorigin="anonymous"></script>
    {% block extrascripts %}{% endblock %}
  </body>
</html>

runreg/templates/layout.html
{% extends "base.html" %}
{% block extrastyles %}
    <link href="{{ url_for('static', filename='css/dashboard.css') }}" rel="stylesheet">
{% endblock %}
{% block extrascripts %}
    <script src="{{ url_for('static', filename='js/dashboard.js') }}"></script>
{% endblock %}
{% block layout %}
    <nav class="navbar navbar-expand-md fixed-top navbar border-bottom border-body">
      <div class="container">
        <a class="navbar-brand" href="{{ url_for('runners.all') }}">Runner Registration</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
          <ul class="navbar-nav me-auto mb-2 mb-md-0">
            <li class="nav-item">
              <a class="nav-link btn btn-outline-primary" aria-current="page" href="{{ url_for('runners.register') }}">New Runner</a>
            </li>
          </ul>
          <div class="d-flex">
            <a class="btn btn-outline-secondary" href="{{ url_for('auth.logout') }}">Logout</a>
          </div>
        </div>
      </div>
    </nav>
    <main class="container">
      {% block content %}{% endblock %}
    </main>
{% endblock %}

runreg/templates/login.html
{% extends "base.html" %}
{% block extrastyles %}
    <link href="{{ url_for('static', filename='css/login.css') }}" rel="stylesheet">
{% endblock %}
{% block bodyclasses %}d-flex align-items-center py-4 bg-body-tertiary{% endblock %}
{% block layout %}
<main class="form-signin w-100 m-auto">
  <form action="{{ url_for('auth.login') }}" method="post">
    <div class="mb-4 w-100 m-auto text-center">
      <img src="{{ url_for('static', filename='images/server.svg') }}" alt="" width="72" height="57">
      <span class="h5">Runner Registration</span>
    </div>
    <h1 class="h3 mb-3 fw-normal">Please sign in</h1>

    <div class="form-floating">
      <input type="email" class="form-control" id="email" name="email" placeholder="name@example.com">
      <label for="email">Email address</label>
    </div>
    <div class="form-floating">
      <input type="password" class="form-control" id="password" name="password" placeholder="Password">
      <label for="password">Password</label>
    </div>

    <div class="form-check text-start my-3">
      <input class="form-check-input" type="checkbox" value="remember-me" id="remember">
      <label class="form-check-label" for="remember">
        Remember me
      </label>
    </div>
    <button class="btn btn-primary w-100 py-2" type="submit">Sign in</button>
    <p class="mt-5 mb-3 text-body-secondary">&copy; 2023 OpenLP Developers</p>
  </form>
</main>
{% endblock %}

runreg/templates/register.html
{% extends "layout.html" %}
{% block content %}
      <h1 class="h2">New Runner</h1>
      <form action="{{ url_for('runners.register') }}" method="post" class="mb-5">
        <div class="mb-3">
          <label for="name">Name <span class="text-danger" title="Required">*</span></label>
          <input type="text" class="form-control" id="name" name="name" placeholder="e.g. intel-mac" required>
        </div>
        <div class="mb-3">
          <label for="description">Description</label>
          <input type="text" class="form-control" id="description" name="description" placeholder="e.g. A GitLab Runner on an Intel Mac for John's pipelines">
        </div>
        <div class="mb-3">
          <label for="token">Token <span class="text-danger" title="Required">*</span></label>
          <input type="text" class="form-control" id="token" name="token" placeholder="e.g. d8Gd4T6xV" required>
        </div>
        <div class="mb-3">
          <label for="runner-type">Type <span class="text-danger" title="Required">*</span></label>
          <select class="form-select" name="runner-type" id="runner-type" aria-label="Runner type" required>
            <option value="" selected>Select a runner type</option>
            {% for runner_type in runner_types %}
            <option value="{{ runner_type.id }}">
            {{ runner_type.name }} ({{ runner_type.tags | map(attribute='name') | join(', ') }})
            </option>
            {% endfor %}
          </select>
        </div>
        <div>
          <button type="submit" class="btn btn-success">Register</button>
          <a type="button" class="btn btn-danger" href="{{ url_for('runners.all') }}">Cancel</a>
        </div>
      </form>
      <div class="card">
        <h5 class="card-header">How to register your GitLab runner</h5>
        <div class="card-body">
          <ol>
            <li>Select the type of runner from the dropdown. Note the tags in brackets.</li>
            <li>
              Go to the CI/CD settings page of your fork of OpenLP.
              <ol type="a">
                <li>Go to your profile</li>
                <li>Click on "Personal projects"</li>
                <li>Click on "OpenLP"</li>
                <li>In the left hand panel, expand "Settings"</li>
                <li>Click on "CI/CD"</li>
              </ol>
            </li>
            <li>
              Register a new runner on the CI/CD page.
              <ol type="a">
                <li>Expand the "Runners" section</li>
                <li>Scroll down to the "Project runners" section</li>
                <li>Click on the "New project runner" button</li>
                <li>Select "macOS" for the Mac runners</li>
                <li>In the "Tags" section, type in the tags from the Type dropdown</li>
                <li>Scroll down and click the "Create runner" button</li>
              </ol>
            </li>
            <li>On the runner summary page, copy the token</li>
            <li>Return to this page, and paste the token in</li>
            <li>Give your runner a name</li>
            <li>Click the "Register" button</li>
            <li>Wait about 5 minutes for the registration process to kick off.</li>
          </ol>
        </div>
      </div>
{% endblock %}

runreg/templates/runners.html
{% extends "layout.html" %}
{% block content %}
<h1 class="h2">Registered runners</h1>
      <div class="table-responsive small">
        <table class="table table-striped table-sm">
          <thead>
            <tr>
              <th scope="col">#</th>
              <th scope="col">Name</th>
              <th scope="col">Description</th>
              <th scope="col">Type</th>
              <th scope="col">Status</th>
              <th scope="col">Tags</th>
            </tr>
          </thead>
          <tbody>
{% for runner in runners %}
            <tr>
              <td>{{ runner.id }}</td>
              <td>{{ runner.name }}</td>
              <td>{{ runner.description }}</td>
              <td>{{ runner.runner_type.name }}</td>
              <td>{{ runner.status.name }}</td>
              <td>
                {% for tag in runner.runner_type.tags %}
                <span class="badge text-bg-info">{{ tag.name }}</span>
                {% endfor %}
              </td>
            </tr>
{% endfor %}
          </tbody>
        </table>
      </div>
{% endblock %}